### ISSUE TITLE
Read only cluster connection support

### ISSUE THREAD

**Issue by vineetgoel** [NoneGG/aredis#101]
Not sure if this already exists but I could not find support for cluster connections where I can enable requests to go to the replica nodes. This is available in the synchronous client as documented here: https://redis-py-cluster.readthedocs.io/en/master/readonly-mode.html

Wondering if there are plans for adding support for a readonly mode.

**Comment by NoneGG** [comment]
@vineetgoel This is also one of the features planted from redis-py-cluster(gratitude for the great work of Grokzen )
You can use it by adding `readonly=True` when initialize an instance of `StrictRedisCluster`
