### ISSUE TITLE
PubSubWorkerThread._run() fails if stream_timeout is used

### ISSUE THREAD

**Issue by barbieri** [NoneGG/aredis#106]
If you use `stream_timeout=1`, the `PubSubWorkerThread` will fail with `TimeoutError` exception, since the `pubsub.get_message()` internally uses `parse_response(block=False, timeout=0)` (since 0 is the default timeout value, and we can't explicitly pass one), which ends using the `stream_timeout=1`.

I see two ways of solving this:
1.  `try-except TimeoutError: pass` around `pubsub.get_message()` at `PubSubWorkerThread._run()`.
2. give `pubsub.get_message(..., timeout=1)`, so we use the `wait_for()` path in `parse_response()`.

I tried both and they work. Let me know your preference and I'll submit the patch (or please fix it, should be 1-2 lines of patch :-D)

**Comment by NoneGG** [comment]
@barbieri I think the second way may be better~
