### ISSUE TITLE
Use of threading.local in lock.py can cause token leakage

### ISSUE THREAD

**Issue by eirikur-grid** [NoneGG/aredis#119]
The use of `threading.local()`in lock.py appears to have been ported directly from redis-py over to this project. As far as I can tell, this can lead to tokens leaking between asynchronous tasks executed within the same event loop (i.e. on the same thread).

Let's consider the following scenario:
 - Task A successfully acquires a lock using token `a` and a timeout of 3 seconds
 - Task B requests the lock with `blocking=True` and `blocking_timeout=None`
 - Task A takes longer than 3 seconds to finish and so the lock is automatically released
 - Task B now successfully holds the lock with token `b`, which is placed in thread local storage
 - Task A finishes and attempts to release the lock. It retrieves the token `b` from thread local storage and is successful in releasing the lock, as opposed to getting a `LockError` due to a token mismatch as would be the correct behavior.

**Comment by NoneGG** [comment]
@eirikur-grid Thanks for bug report, i will check it and give my feedback as soon as possible.

**Comment by NoneGG** [comment]
@eirikur-grid I am afraid you are right, different coroutines share the same thread, which will break the safety of thread local mechanism. In Python 3.7 i can use contextvars to fix this, i will see if there is a good solution in Python 3.6

**Comment by NoneGG** [comment]
@eirikur-grid 
I found a backport of `contextvars` for 3.5/3.6[package](https://pypi.org/project/contextvars/), this bug will be fixed soon, thanks again for bug report

**Comment by NoneGG** [comment]
Just to be additional, I try to reproduce the scene you described and find out that the problem will only take place when one clock is shared between multiple coroutine just like:
```Python
async def test():
    r = StrictRedis()
    lock_b = lock_a = r.lock(lock_key, timeout=3)
    print(lock_a.local.token)
    # lock_b = r.lock(lock_key)
    print(lock_b.local.token)
    print(id(lock_b) == id(lock_a))

    res = await lock_a.acquire()
    print('thread a acquire token: {} ts: {} res: {}'.format(lock_a.local.token, time.time(), res))
    print(lock_a.local.__dict__)
    print(lock_b.local.__dict__)
    res = await lock_b.acquire(blocking=True)
    print('thread b acquire token: {} ts: {} res: {}'.format(lock_b.local.token, time.time(), res))
    print(lock_a.local.__dict__)
    print(lock_b.local.__dict__)

    await asyncio.sleep(2)
    try:
        print('thread a release token: {} ts: {}'.format(lock_a.local.token, time.time()))
        print(await r.get(lock_key))
        await lock_a.release()
    except Exception as exc:
        print('thread_a failed to release due to: {} token: {} ts: {}'.format(exc, lock_a.local.token, time.time()))

    try:
        print('thread b release token: {} ts: {}'.format(lock_b.local.token, time.time()))
        print(await r.get(lock_key))
        await lock_b.release()
    except Exception as exc:
        print(exc)

```
If i initialize another lock instance with the same key, there will be a new threading_local object and `lock.local.token` will not be covered.

However, i can not limit user the way they use the lock, i will fix it soon

**Comment by NoneGG** [comment]
@eirikur-grid The fix is finished, would you like to see it ? It will be merged If there is no other problem :-)

**Comment by NoneGG** [comment]
@eirikur-grid Merged, thanks again for bug report~

**Comment by eirikur-grid** [comment]
> @eirikur-grid The fix is finished, would you like to see it ? It will be merged If there is no other problem :-)

Sorry for the late reply. I somehow missed the e-mail notification. I'll take a post-merge look and attempt to verify the fix.

**Comment by eirikur-grid** [comment]
@NoneGG I have verified that the fix works as intended. However, I noticed that the newly added test is failing. See: https://github.com/NoneGG/aredis/pull/120/files#r317581785
