### ISSUE TITLE
[Help Wanted] Want to use aredis pubsub in tornado, but I can't find related docs

### ISSUE THREAD

**Issue by liuzhuoling2011** [NoneGG/aredis#128]
## Checklist

- Python version 3.7.3
- Using Python parser 
- Using just asyncio event loop
- Does issue exists against the `master` branch of aredis? Yes

## Expected behavior
Want to use aredis pubsub in tornado(websocket), but I can't find related docs
Could you show me a demo?  Thanks

**Comment by NoneGG** [comment]
@liuzhuoling2011

**Comment by liuzhuoling2011** [comment]
It works, thanks~

**Comment by liuzhuoling2011** [comment]
Want to call aredis subscribe function when tornado server start, something like this:
```python
async def subscribe_redis(self):
    redis = StrictRedis(...).pubsub(ignore_subscribe_messages=True)
    redis.subscribe(...)
    while True:
        await redis.get_message(timeout=1)
        await asyncio.sleep(0.001)
```
Could you give me an elegant example? Thx

**Comment by NoneGG** [comment]
@liuzhuoling2011 I am not sure about your requirement, it seems like you want to make a while loop after tornado server started? It may be better to run it in another thread / process

**Comment by liuzhuoling2011** [comment]
@NoneGG We have some bussiness data continuously published to redis, and we want to use tornado websocket push these data to the web ui. For better performance, we want redis subscribe and tornado working in a same thread

**Comment by NoneGG** [comment]
@liuzhuoling2011 May this [example](https://github.com/shafayeatsumit/tornado-redis-pubsub-example) be helpful, check if it is suitable for your scene~
