### ISSUE TITLE
[Help Wanted] Pubsub occasionally crash problem

### ISSUE THREAD

**Issue by liuzhuoling2011** [NoneGG/aredis#129]
## Checklist

- Python version 3.7.3
- Using just Python parser
- Using just asyncio event loop
- Does issue exists against the `master` branch of aredis? Yes

## Steps to reproduce
My project subscribe 4 channels to recieve signals, aredis works perfectly at most of the time, but occasionally it will cause system crash

## Expected behavior
Never crash

## Actual behavior
Below is my pseudo codes:
```python
        r = StrictRedis(host=conf[0], port=conf[1], password=conf[2], db=conf[3], decode_responses=True)
        p = r.pubsub(ignore_subscribe_messages=True)
        
        def demo_func(message):
            pass

        subscribe = {
            'demo_key1': demo_func,
            'demo_key2': demo_func,
            'demo_key3': demo_func,
            'demo_key4': demo_func,
        }
        await p.subscribe(**subscribe)
        
        while True:
            try:
                await p.get_message(timeout=0.1)
                await asyncio.sleep(0.001)
            except Exception as e:
                print(e)
```

Below is call stack from `Sentry`:
![image](https://user-images.githubusercontent.com/8407297/71340650-782eb000-2592-11ea-8a24-13a368290303.png)

**Comment by NoneGG** [comment]
@liuzhuoling2011 With which release of redis server are you using?

**Comment by liuzhuoling2011** [comment]
redis_version: 3.2.6
redis_mode: standalone
os: Linux 4.9.0-6-amd64 x86_64
arch_bits: 64
multiplexing_api: epoll
gcc_version: 6.2.1

**Comment by NoneGG** [comment]
@liuzhuoling2011 I try to reproduce your scene bu failed.

* problem:
It seems like your redis-server send back 'OK' and there is something wrong with reponse parsing (message type is at head of reponse usually) or redis (maybe it doesn't send back message type) 

* advice:
try hiredis instead of raw python parser to see if this problem can be reproduce
(actually the socket buffer processing can also lead to similar problem, so for now there can't be a conclusion)

**Comment by liuzhuoling2011** [comment]
Thanks for your advice, I will try and return the feedback

**Comment by NoneGG** [comment]
@liuzhuoling2011 Does that problem happen again?

**Comment by liuzhuoling2011** [comment]
Currently not happen, Thx
