### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bsergean** [NoneGG/aredis#142]
Hey @NoneGG are you planning on making a new release soon?
(so I can try to use the version with my bug fixes)
Thanks !

**Comment by NoneGG** [comment]
@bsergean Sure, i will fix some bugs raised in issue #140 & #141 . New release will be public in two days.

**Comment by NoneGG** [comment]
@bsergean Release v1.1.8 is public now, just try it~

**Comment by bsergean** [comment]
Thanks !
