### ISSUE TITLE
ERROR sending "cluster slots" 

### ISSUE THREAD

**Issue by melhin** [NoneGG/aredis#26]
Im getting 

ERROR:root:ERROR sending "cluster slots" command to redis server: {'port': 7002, 'host': '127.0.0.1'}

When i try to use the StrictRedisCluster Connection

On further debugging i found that 
parse_cluster_slots  in commands/cluster is looking for node[2] which somehow doesnt come in the cluster slots command run from the redis-cli

I run cluster slots
127.0.0.1:7001> cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 7004
   4) 1) "127.0.0.1"
      2) (integer) 7003
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 7006
   4) 1) "127.0.0.1"
      2) (integer) 7005
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 7001
   4) 1) "127.0.0.1"
      2) (integer) 7002

and run cluster nodes
7a3710105e20a9b30d81f636b2b30d27218dc0ac 127.0.0.1:7003 slave 3ee92494550369062d5ff5cbd9b3b5efd60f6c01 0 1494940935358 24 connected
4ace8f1ceb4be131884fe0df0ca50ec576f2909a 127.0.0.1:7002 slave aa10e2d760478d6e7e5a1627379acd508726bf67 0 1494940934858 22 connected
3ee92494550369062d5ff5cbd9b3b5efd60f6c01 127.0.0.1:7004 master - 0 1494940936361 24 connected 5461-10922
41a63b873a2257af9866db482dd35f016f204f93 127.0.0.1:7006 master - 0 1494940936361 21 connected 10923-16383
aa10e2d760478d6e7e5a1627379acd508726bf67 127.0.0.1:7001 myself,master - 0 0 22 connected 0-5460
b00c4d9e1d404b5e35b58a664284fe274e111523 127.0.0.1:7005 slave 41a63b873a2257af9866db482dd35f016f204f93 0 1494940935859 21 connected

**Comment by NoneGG** [comment]
@melhin Hey, melhin, could you tell me how you deploy your redis cluster please? It seems like there are unknown error when you use StrictRedisCluster Connection. The error handling logic is like below (in `NodeManager.initialize`):

``` Python
for node in nodes:
     try:
        r = self.get_redis_link(host=node['host'], port=node['port'])
        cluster_slots = await r.cluster_slots()
        startup_nodes_reachable = True
    except ConnectionError:
        continue
    except Exception:
        raise RedisClusterException('ERROR sending "cluster slots" command to redis server: {0}'.format(node))
```

I try to reproduce your problem by code like below (i use docker in my development env, so i can access the cluster from `127.0.0.1` but the cluster thinks itself launched from `172.17.0.2`), the print result in in annotation:
``` Python
#!/usr/bin/python
# -*- coding: utf-8 -*-

import asyncio
from aredis import StrictRedisCluster
from aredis.connection import ClusterConnection
from aredis.commands.cluster import parse_cluster_slots


async def example():
    cluster = StrictRedisCluster(startup_nodes=[{'host': '127.0.0.1', 'port': 7002}])
    print(await cluster.cluster_slots())
    """
    {(10923, 16383): [
    {'node_id': b'7263d083837d9ed872123c1703e5d0f60dfe5a0c', 'host': b'172.17.0.2', 'port': 7002, 'server_type': 'master'},
    {'node_id': b'301f61c9553823fe526e81e69b4c89da7dafd5e0', 'host': b'172.17.0.2', 'port': 7005, 'server_type': 'slave'}
    ],
    (5461, 10922): [
    {'node_id': b'f1f08a81f4afd4bb5daaa44d3701175f57728cbc', 'host': b'172.17.0.2', 'port': 7001, 'server_type': 'master'},
    {'node_id': b'9ce65b448234223a9c92ec9c442ca3f3aeeefeb0', 'host': b'172.17.0.2', 'port': 7004, 'server_type': 'slave'}
    ],
    (0, 5460): [
    {'node_id': b'7172e3c463b79ef11cceea0da9b2ca91f9b1bc93', 'host': b'172.17.0.2', 'port': 7000, 'server_type': 'master'},
    {'node_id': b'06ae04a0320ad4b3654f469b3ffa6646a31cd3cb', 'host': b'172.17.0.2', 'port': 7003, 'server_type': 'slave'}
    ]
    }
    """
    conn = ClusterConnection(host='127.0.0.1', port=7002)
    await conn.send_command('cluster slots')
    res = await conn.read_response()
    print(res)
    assert parse_cluster_slots(res) == await cluster.cluster_slots()
    """
    [
    [
    5461, 10922,
    [b'172.17.0.2', 7001, b'f1f08a81f4afd4bb5daaa44d3701175f57728cbc'],
    [b'172.17.0.2', 7004, b'9ce65b448234223a9c92ec9c442ca3f3aeeefeb0']
    ],
    [
    10923, 16383,
    [b'172.17.0.2', 7002, b'7263d083837d9ed872123c1703e5d0f60dfe5a0c'],
    [b'172.17.0.2', 7005, b'301f61c9553823fe526e81e69b4c89da7dafd5e0']
    ],
    [0, 5460,
    [b'172.17.0.2', 7000, b'7172e3c463b79ef11cceea0da9b2ca91f9b1bc93'],
    [b'172.17.0.2', 7003, b'06ae04a0320ad4b3654f469b3ffa6646a31cd3cb']
    ]
    ]
    """

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(example())
```
And the picture is what i got from my redis cli, it seems to work well.
![image](https://cloud.githubusercontent.com/assets/22073484/26114812/e4cb83d6-3a90-11e7-8c9b-3994f0762699.png)

**Comment by melhin** [comment]
@NoneGG  i saw that the error occurs in 
```
for node in nodes:
     try:
        r = self.get_redis_link(host=node['host'], port=node['port'])
        cluster_slots = await r.cluster_slots()
        startup_nodes_reachable = True
    except ConnectionError:
        continue
    except Exception:
        raise RedisClusterException('ERROR sending "cluster slots" command to redis server: {0}'.format(node))
```

On further traceback i found that in this function


```
def parse_cluster_slots(response):
    res = dict()
    for slot_info in response:
        min_slot, max_slot = slot_info[:2]
        nodes = slot_info[2:]
        parse_node = lambda node: {
            'host': node[0],
            'port': node[1],
            'node_id': node[2],
            'node_id': 0,
            'server_type': 'slave'
        }
        res[(min_slot, max_slot)] = [parse_node(node) for node in nodes]
        res[(min_slot, max_slot)][0]['server_type'] = 'master'
    return res

```
node_id is assigned to node[2] which in my case doesn't come

as you can see 
cluster slots
gives something like this 
```
127.0.0.1:7001> cluster slots

(integer) 5461
(integer) 10922
"127.0.0.1"
(integer) 7004
"127.0.0.1"
(integer) 7003

```
so from it you see there is no id parameter so the length of array in cluster slot response is just 2
when i run 
```
127.0.0.1:7001> cluster nodes
7a3710105e20a9b30d81f636b2b30d27218dc0ac 127.0.0.1:7003 slave 3ee92494550369062d5ff5cbd9b3b5efd60f6c01 0 1494940935358 24 connected
4ace8f1ceb4be131884fe0df0ca50ec576f2909a 127.0.0.1:7002 slave aa10e2d760478d6e7e5a1627379acd508726bf67 0 1494940934858 22 connected
```
i get the id though .

**Comment by NoneGG** [comment]
@melhin 
I get your point, that is a bug indeeed, which according to the [document](https://redis.io/commands/cluster-slots), is different in different version of redis server. I will try to make it compatible as soon as possible.
Thank you for bug report, that is really helpful! You will be informed immediately once the bug is fixed~

**Comment by NoneGG** [comment]
@melhin 
The bug is fixed~ 
Thank you for your bug report, if there are more advices or idea, please let me know, thaks~
