### ISSUE TITLE
can't random choice on a dict

### ISSUE THREAD

**Issue by myrfy001** [NoneGG/aredis#47]
in pool.py, get_random_connection() try to use random.choice() on a dict. It is wrong.

**Comment by myrfy001** [comment]
The detail is , if a redis cluster has set the timeout, and the request count to redis server is very small, some idel connection will be closed by the server. And when the request come, aredis will try to use a random connection, then, `return random.choice(self._available_connections)` will fail.

**Comment by NoneGG** [comment]
@myrfy001 
Thank you for the bug report~
The bug is fixed and pushed to master with some other changes(actually i am trying to add support for transaction on single node of a cluster)

You can try the fixed version by `pip install git+https://github.com/NoneGG/aredis.git`
