### ISSUE TITLE
pipeline  when transaction=True error; but transaction=False pass 

### ISSUE THREAD

**Issue by dangerousfeng** [NoneGG/aredis#54]
Traceback (most recent call last):
  File "/home/chaos_session/chaos_session/route.py", line 65, in exec_action
    result = await class_obj.exec_action()  # 执行对象的exec_action方法d
  File "/home/chaos_session/chaos_session/tool/action_base.py", line 136, in exec_action
    await self.take_action()
  File "/home/chaos_session/chaos_session/tool/action_base.py", line 118, in take_action
    await self.do_action()
  File "/home/chaos_session/chaos_session/v1_2/game_1010/action20000.py", line 35, in do_action
    c_pub=self.c_pub)
  File "/home/chaos_session/chaos_session/db_manager/user_info_manager.py", line 50, in add_user
    await self.db.insert_one(JWT, user)
  File "/home/chaos_session/chaos_session/db_manager/redis_manage.py", line 228, in insert_one
    await self._insert_one(wrapper_jwt, data)
  File "/home/chaos_session/chaos_session/db_manager/redis_manage.py", line 218, in _insert_one
    r = await self.pipe.execute()
  File "/home/py3-env/lib/python3.5/site-packages/aredis/pipeline.py", line 286, in execute
    return await exec(conn, stack, raise_on_error)
  File "/home/py3-env/lib/python3.5/site-packages/aredis/pipeline.py", line 203, in _execute_transaction
    if isinstance(response, typing.Awaitable):
AttributeError: module 'typing' has no attribute 'Awaitable'

**Comment by NoneGG** [comment]
The error seems to be caused by `AttributeError: module 'typing' has no attribute 'Awaitable'`, but in my dev env(Python3.5.3) typing package do has attribute `Awaitable`. I am not sure if this is caused by the difference among Python3.5 releases. 
Could you tell me with which release of Python3.5 are you working?

**Comment by dangerousfeng** [comment]
oh，it's Python 3.5.0

**Comment by dangerousfeng** [comment]
Now i use python3.5.2, it run, thank you!

**Comment by dangerousfeng** [comment]
Do you have any other examples of XX? Can you give me some information? Thanks very much！

**Comment by dangerousfeng** [comment]
Do you have any other examples of  pipeline? Can you give me some information? Thanks very much!

**Comment by NoneGG** [comment]
That's an issue indeed, i will try to support coroutine judgement in Python3.5.0.
About the example of pipeline, you could see code [here](https://github.com/NoneGG/aredis/blob/master/examples/pipeline.py) 
Let me know if you still have problem about that~

**Comment by dangerousfeng** [comment]
I want to implement a RedisManager, and now my idea is as follows:，do you think there is no error in the structure, is there a better way?

`class RedisManager(object):

    def __init__(self, server_id,app_id = 0):
        self.server_id = server_id
        self.app_id = app_id
        self.conn = aredis.StrictRedis(connection_pool=my_redis_pool,connect_timeout=5, retry_on_timeout=5)
        self.pipe = None
        
    async def is_exist(self, key):
        if self.pipe is None:
            async with await self.conn.pipeline(transaction=True) as pipe:
                self.pipe=pipe
        await self.pipe.exists(key)
        r = await self.pipe.execute()
        if r[-1]:
            return True
        else:
            return False

    async def check(self,key):
        if self.pipe is None:
            async with await self.conn.pipeline(transaction=True) as pipe:
                self.pipe=pipe
        await self.pipe.hget(key)
        r = await self.pipe.execute()
        return r[-1]
    
    async def find(self,match):
        s = self.conn.register_script(MY_SCRIPT)
        res = await s.execute(args=[match])
        return res
    
    ...`

**Comment by NoneGG** [comment]
@dangerousfeng 
I read your code(have not run yet) and find some problems:

1. StrictRedis is a client which can hold multi connections, naming it as `self.conn` seems not appropriate
2. The pipe is shared in the object(if instantiated), which seems meaningless, all operation of pipeline is packaged in your functions and not shared.(ignore this if there are other usage of pipeline between two functions)
3. `self.pipe.exists`, `self.pipe.hget` and `self.pipe.execute` is assumed to run in the contextmanager generated by `async with self.conn.pipeline(transaction=True) as pipe` some clean job will be executed after the contextmanager end. And now it won't be executed in your code.
4. since all of your function only contains one command like `hget` and `exists`, pipeline and transaction is not needed. Pipeline is used to send multi commands in one network communication to reduce time spent on IO.

For now, i can only see these problems, if you still have other problems, please let me know.

**Comment by dangerousfeng** [comment]
I want to share pipe in the object, but I don't know how to implement it.

**Comment by dangerousfeng** [comment]
噢！我发现你在上海！
我希望能够在类实例化的时候得到pipeline，然后在其他函数里面调用self.pipe就可以使用。也就是所有函数共用一个pipeline。这样可以做到吗？不希望在每个函数里面都做
async with await       self.conn.pipeline(transaction=True) as pipe:这一步。我现在使用了sanic uvloop  aredis，但是性能上面较flask提升不大。我现在在排查问题，认为是redis这部分异步有问题。
真的很感谢你！

**Comment by NoneGG** [comment]
可以的，不用 `async with` 进入上下文管理器，如果不涉及多进程多线程的话在实例化的时候直接 `self.pipe = self.conn.pipeline(transaction=True)` 即可， pipeline 对象在调用 `execute` 后会做 `reset` 操作，不过在你的类对象析构的时候最好还是带上 `self.pipe.reset`。
我对 benchmark 很感兴趣，不知道你这边是一个什么类型的 web 应用，是怎样进行的性能测试？

**Comment by dangerousfeng** [comment]
实例化：
```
self.client = aredis.StrictRedis(connection_pool=config_manager_list[str(app_id)].redis_pool, 
                                               connect_timeout=5, retry_on_timeout=5)
        self.pipe = self.client.pipeline(transaction=True)
```
函数调用：
    ```
async def insert_index(self, filters, JWT): 
        wrapper_jwt = self.wrapper_JWT(JWT)
        wrapper_uid = self.wrapper_UID(filters["Uid"])
        wrapper_rid = self.wrapper_RID(filters["Rid"])
        await self.pipe.set(wrapper_uid, wrapper_jwt)
        await self.pipe.set(wrapper_rid, wrapper_jwt)
        await self.pipe.expire(wrapper_uid, self.expire_time)
        await self.pipe.expire(wrapper_rid, self.expire_time)
        r = await self.pipe.execute()
```
报错：
`File "/home/chaos_session/chaos_session/db_manager/redis_manage.py", line 199, in _insert_one
    await self.pipe.hmset(JWT, data)
AttributeError: 'coroutine' object has no attribute 'set'`   
另一种调用方式：
```
async def is_exist(self, key):

async def check(self,key):

async def insert_index(self, filters, JWT): 
        pipe = await self.pipe
        wrapper_jwt = self.wrapper_JWT(JWT)
        wrapper_uid = self.wrapper_UID(filters["Uid"])
        wrapper_rid = self.wrapper_RID(filters["Rid"])
        await pipe.set(wrapper_uid, wrapper_jwt)
        await pipe.set(wrapper_rid, wrapper_jwt)
        await pipe.expire(wrapper_uid, self.expire_time)
        await pipe.expire(wrapper_rid, self.expire_time)
        r = await pipe.execute()
```
报错：
`File "/home/chaos_session/chaos_session/db_manager/redis_manage.py", line 257, in insert_index
    pipe = await self.pipe
RuntimeError: cannot reuse already awaited coroutine`

**Comment by NoneGG** [comment]
不好意思，是我的疏漏，`self.pipe = self.conn.pipeline(transaction=True)` 前要加上一个 `await`， 应该是 `self.pipe = await self.conn.pipeline(transaction=True)`，`StrictRedis.pipeline(transaction=True)` 是一个需要 `await` 的协程

**Comment by dangerousfeng** [comment]
但是init构造函数里面不可以使用await吧

**Comment by NoneGG** [comment]
是这样的，你可以选择在 init 函数内置为 None 然后要用到的时候通过协程来赋值

**Comment by dangerousfeng** [comment]
嗯嗯，可以啦。我现在试图提升会话服务项目的性能，之前采用flask框架。希望通过sanic重构，配合uvloop，提升性能，但是目前的效果就是RPS比flask时提升一倍，但是并没有像网上说的好几倍，只是和pypy下的flask性能差不多。

**Comment by NoneGG** [comment]
裸性能来说用 asyncio 其实是较慢的，他的优势在于低开销地处理大量请求，采用多线程模型的话可能对大量请求是可能hang住的。会不会是你这边性能测试的时候没有模拟业务环境（带上数据库或者文件io），只是纯粹拼 helloworld 的请求的话不一定能测出你服务的真实性能提升。
你这边有发现性能瓶颈么？可以 profile 看一下~这个问题其实很重要，如果确认是 aredis 导致的请告诉我，我会尽可能优化。
不介意的话这个 issue 我就关闭了
