### ISSUE TITLE
TSL connection to AWS redis cluster

### ISSUE THREAD

**Issue by stj** [NoneGG/aredis#68]
## Checklist

- Python version
3.6.3
- Using hiredis or just Python parser
hiredis
- Using uvloop or just asyncio event loop
asyncio
- Does issue exists against the `master` branch of aredis?
both

## Steps to reproduce
```python
#!/usr/bin/python

import asyncio
import logging
import os
from aredis import StrictRedisCluster
from aredis import ClusterConnectionPool

async def example():
    pool = ClusterConnectionPool.from_url(os.getenv('REDIS_CLUSTER_URL'))
    redis = StrictRedisCluster(connection_pool=pool, decode_responses=False, skip_full_coverage_check=True)
    logging.info(redis.connection_pool.initialized)
    logging.info(redis.connection_pool.nodes.slots.keys())
    await redis.connection_pool.initialize()
    logging.info(redis.connection_pool.initialized)
    logging.info(redis.connection_pool.nodes.slots[15495])
    logging.info(await redis.get('a'))

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(example())
```
```bash
export REDIS_CLUSTER_URL=rediss://:###@###.cache.amazonaws.com:7000/0
```

## Expected behavior
Connects and does not raise exception

## Actual behavior
```python
INFO:root:False
INFO:root:dict_keys([])
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aredis/nodemanager.py", line 123, in initialize
    r = self.get_redis_link(host=node['host'], port=node['port'])
  File "/usr/lib/python3.6/site-packages/aredis/nodemanager.py", line 98, in get_redis_link
    return StrictRedis(host=host, port=port, decode_responses=True, **connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl_context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debug_redis.py", line 24, in <module>
    loop.run_until_complete(example())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "debug_redis.py", line 15, in example
    await redis.connection_pool.initialize()
  File "/usr/lib/python3.6/site-packages/aredis/pool.py", line 299, in initialize
    await self.nodes.initialize()
  File "/usr/lib/python3.6/site-packages/aredis/nodemanager.py", line 129, in initialize
    raise RedisClusterException('ERROR sending "cluster slots" command to redis server: {0}'.format(node))
aredis.exceptions.RedisClusterException: ERROR sending "cluster slots" command to redis server: {'host': '###.cache.amazonaws.com', 'port': '###'}
```

**Comment by NoneGG** [comment]
@stj 
Thank you for your detailed issue~
This bug can be reproduced in my test env (even not aws) simply by using url to connect to redis cluster. (although it will block if the cluster do not support ssl)

If you don't mind , could you use the master branch code to go on your test and see if it can work well in aws env? (Since this is the second issue related to aws redis cluster, i try to register an aws account and finally give up because my debit card never pass the check for unknown reason)

Please tell me if there are still other problems, i will fix it as soon as possible.

**Comment by stj** [comment]
Haven't had a chance to test this against AWS redis cluster. Hope I have time to do so this week.
Thanks for jumping on the issue that fast!

**Comment by stj** [comment]
Finally had a chance to test this and it does not throw the error anymore 👍. 

Though I have not been able to connect to AWS redis either. `await redis.connection_pool.initialize()` times out with `aredis.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.` Problem is that I have no access to AWS console to check what my OPS team has set up.

Closing issue, since the bug I reported is fixed. Thx!

**Comment by NoneGG** [comment]
@stj 
Thank you for your test and feedback~
