### ISSUE TITLE
Connecting with Redis URL?

### ISSUE THREAD

**Issue by crinny** [NoneGG/aredis#71]
How can i connect to databse with such string as `redis://h:p5ef9a0cfbef0io972d83933b10d99bc7d5d4a1ec777db341c6b12310f47e2cea@ec2-52-212-239-249.kabab.com:12345`?

**Comment by NoneGG** [comment]
@crinny 
You can connect to redis using code like `StrictRedis.from_url(your_url)`

**Comment by NoneGG** [comment]
This issue will be closed now, if you have other problems about that, it is welcomed to be open again~
