### ISSUE TITLE
Possible to cut a new version with the added zaddoption feature?

### ISSUE THREAD

**Issue by pliu** [NoneGG/aredis#75]
^ Title.

**Comment by NoneGG** [comment]
@pliu 
Actually v1.1.2 is released only a few of days ago(without zaddoption included), the timing is not so good regretfully.
If you don't mind, could you tell me why a new version is needed so urgently? 
It is enough to install by command 
`pip install git+https://github.com/NoneGG/aredis` 
if you only use aredis in dev env, or are you goingto use aredis in production env?

**Comment by pliu** [comment]
Was actually planning on running it in production :P

**Comment by NoneGG** [comment]
v1.1.3 is released~
