### ISSUE TITLE
Moved error

### ISSUE THREAD

**Issue by vineetgoel** [NoneGG/aredis#76]
I am using StrictRedisCluster.

I am getting a bunch of MovedErrors. Is there some setting I need to set to allow for redirections upon cluster movements?

**Comment by NoneGG** [comment]
@vineetgoel 
This problem is not thought about before, actually `MovedError` will not be raised in aredis client(this kind of exception is handled automatically by client itself), it will only update node-slot cache instead. 
If you don't mind, could you give me detailed log of your app?

**Comment by NoneGG** [comment]
@vineetgoel If you don't mind, this issue will be closed. Please feel free to reopen it~

**Comment by vineetgoel** [comment]
Sorry about ghosting this thread. I have not been able to see the error again. I will add it here and reopen if I can find it.
