### ISSUE TITLE
redis.pubsub().listen() does not work properly

### ISSUE THREAD

**Issue by penguinol** [NoneGG/aredis#79]
## Checklist

- Python 3.5.1/Python 3.6
- Python parser
- event loop
- 1.1.2

## Steps to reproduce
```python
from aredis import StrictRedis
import asyncio


def on_message(message):
    print(message)


async def sub_redis():
    redis = StrictRedis('127.0.0.1', 6379)
    redis_sub = redis.pubsub()
    await redis_sub.subscribe('notify')
    for message in await redis_sub.listen():
        print(message)


if __name__ == '__main__':
    task = sub_redis()
    asyncio.ensure_future(task)
    asyncio.get_event_loop().run_forever()
```

redis-cli publish notify bye

## Expected behavior
with redis-py, it's output is as blow:
{'type': 'subscribe', 'pattern': None, 'channel': b'notify', 'data': 1}
{'type': 'message', 'pattern': None, 'channel': b'notify', 'data': b'bye'}

## Actual behavior
with aredis it's output is:
> type
> pattern
> channel
> data

and it can't receive follow-up messages

**Comment by NoneGG** [comment]
@penguinol 
Thank your for your detailed bug report.
Actually, the response given back from `redis_sub.listen()` is `dict`, and the output printed are actually the keys, by the way, `block=True` is used to indicate if timeout is set on the coroutine used to read response.

Please try code below:
```
from aredis import StrictRedis
import asyncio


def on_message(message):
    print(message)


async def sub_redis():
    redis = StrictRedis('127.0.0.1', 6379)
    redis_sub = redis.pubsub()
    await redis_sub.subscribe('notify')

    while True:
        msg = await redis_sub.listen()
        assert isinstance(msg, dict)
        print(msg)


if __name__ == '__main__':
    task = sub_redis()
    asyncio.ensure_future(task)
    asyncio.get_event_loop().run_forever()
```

**Comment by penguinol** [comment]
Your code works fine. So maybe the document should be changed.

http://aredis.readthedocs.io/en/latest/pubsub.html

Older versions of aredis only read messages with pubsub.listen(). listen() is a generator that blocks until a message is available. If your application doesn’t need to do anything else but receive and act on messages received from redis, listen() is an easy way to get up an running.

>>> for message in await p.listen():
...     # do something with the message

**Comment by NoneGG** [comment]
Thank you for your advice~
Since generatior is not allowed in `async` `await` function, there may be difference between redis-py and aredis on that point, i will change the document soon.

**Comment by penguinol** [comment]
Maybe `async for` is a choice

**Comment by NoneGG** [comment]
That seems good~But i think it is better to give the authority to user to decide whether to use `listen` as a generator, if they do, may be they can package code like this.

**Comment by NoneGG** [comment]
This issue is closed, if there are other related problems, please feel free to open it again~
