### ISSUE TITLE
Streams command support?

### ISSUE THREAD

**Issue by myrfy001** [NoneGG/aredis#85]
When will the streams commands be added?

Looking forward for that~

**Comment by NoneGG** [comment]
It's on the way

**Comment by craigglennie** [comment]
@myrfy001 you can use the streams now by calling `execute_command` with your client object. Here's an example:

`await client.execute_command('XADD', 'stream_key', 'MAXLEN', '~', 100, '*', 'field', 'value')`

**Comment by NoneGG** [comment]
@myrfy001 @craigglennie 
Stream support is nearly finished, but i found some part of the commands like `XTRIM`, `XCLAIM` are not released yet and may be changed in next release. For now, I just add related code in [streams branch](https://github.com/NoneGG/aredis/tree/streams)
Would you like to try it? Advice is welcomed. Related detailed test cases will be added soon(it is simply tested for now)

**Comment by myrfy001** [comment]
OK
We are planing to use it in a new project, so we will test it as the project being developed.
