### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by ray1888** [NoneGG/aredis#86]
## Checklist

- Python version 
  3.6
- Using hiredis or just Python parser   
python parser only 
- Using uvloop or just asyncio event loop  
asyncio event loop  
- Does issue exists against the `master` branch of aredis?

## Expected behavior
to get a result is not None with callback

## Actual behavior
- It is appreciated if error log can be provided
is that any possible to add a feature to get the data from redis with special key when the data is not None with a callback?  my situation is in tornado to use celery run the background job , but i have to relay on the celery run result , but i am doing is to get the result if is none , use tornado sleep to wait .
```
# the demo code is something like this 
        while not result:
            await tornado.gen.sleep(0.2)
            result = await self.application.redis_client.get(prefix + task.id)
```
but it do decrese the performance of my web app? so is that any possible way to get the result with callback ?

**Comment by NoneGG** [comment]
If you are using single node or sentinel, there may be a simple way to achieve the result of a callback:
1. register a lua script
    * get value of the key
    * publish the key to a specific topic(using `pubsub` or `stream` or just simple list using `rpop` `lpush`)
2. use tornado ioloop to add a crontab job to check the callback or create another celery job in which you can call another api  of your tornado app to handle the result

I think it is something beyond what a client should do, may it be better to be done by upper layer code.

**Comment by NoneGG** [comment]
@ray1888 This issue is closed now, feel free to open it again~
