### ISSUE TITLE
Order of params in zincby is not the same as in official redis docs

### ISSUE THREAD

**Issue by creotiv** [NoneGG/aredis#87]
https://github.com/NoneGG/aredis/blob/bc75f740744e84b23e1709b7b8bd40ccae154445/aredis/commands/sorted_set.py#L89

docs: https://redis.io/commands/zincrby

**Comment by NoneGG** [comment]
@creotiv 
Thank you for your advice~
The api is ported from redis-py and i think this is more friendly for users(since `amount` is 1 in most part of scene)

**Comment by NoneGG** [comment]
This issue is closed now, feel free to open it again if you still have the problem~
