### ISSUE TITLE
Is StrictRedis retry behaviour as expected?

### ISSUE THREAD

**Issue by ycraaron** [NoneGG/aredis#90]
## Checklist

- Python version
   3.6
- Using hiredis or just Python parser
   Python parser
- Using uvloop or just asyncio event loop
   Asyncio
- Does issue exists against the `master` branch of aredis?
   Yes

## Steps to reproduce
https://github.com/NoneGG/aredis/blob/395ce420a5b477dfb51aa632c15912a1111f40ea/aredis/client.py#L156-L161
During debugging another issue, I find that the logic here is a bit strange.
The senario:
2 different types of errors ConnectionError and TimeoutError will be caught here, and from the following if clause, isinstance(TimoutError) is added as a condition, so I am assuming that the expected behavior for retry is:
1. The user sets the retry_on_timeout to True.
2. It's a TimeoutError.

## Expected behavior
The expect behavior can be interpreted with a truth table(T means do retry, F means not):

|      TimeoutError\retry | true | false | 
|-------|------|:-----:|
| true  | T    |   F   |
| false | F    |   F   |
## Actual behavior
The actual behavior can be interpreted with a truth table(T means do retry, F means not):

|      TimeoutError\retry | true | false | 
|-------|------|:-----:|
| true  | T    |   F   |
| false | T    |   T   |

## Conclusion
If my understanding of the expected behavior is correct, then we need to fix the problem of retrying on encountering connection error.(I already created a PR for it)

Here is a script for validating the current behavior and behavior after the fix:
```python
# script for validating the current and fixed behavior truth table

do_retry =          [True, True, False, False]
is_timeout_error =  [False,True, True,  False]
zipped = list(zip(do_retry, is_timeout_error))

# current behaviour:
print("----------------------------------------")
print("Current behaviour: ")
print("----------------------------------------")
for do_retry, is_timeout_error in zipped:
    print("Condition: retry-{}, timeout-{}".format(do_retry, is_timeout_error))
    if not do_retry and is_timeout_error:
        print("Result: not retry")
    else:
        print("Result: retry")

# behaviour after fix:
print("----------------------------------------")
print("Fixed behaviour: ")
print("----------------------------------------")
for do_retry, is_timeout_error in zipped:
    print("Condition: retry: {}, timeout: {}".format(do_retry, is_timeout_error))
    if not (do_retry and is_timeout_error):
        print("Result: not retry")
    else:
        print("Result: retry")
print("----------------------------------------")
```
Script output:

```
----------------------------------------
Current behaviour:
----------------------------------------
Condition: retry-True, timeout-False
Result: retry
Condition: retry-True, timeout-True
Result: retry
Condition: retry-False, timeout-True
Result: not retry
Condition: retry-False, timeout-False
Result: retry
----------------------------------------
Fixed behaviour:
----------------------------------------
Condition: retry: True, timeout: False
Result: not retry
Condition: retry: True, timeout: True
Result: retry
Condition: retry: False, timeout: True
Result: not retry
Condition: retry: False, timeout: False
Result: not retry
----------------------------------------
```

**Comment by ycraaron** [comment]
Guess this is inherited from redis-py, will create an issue there. https://github.com/andymccurdy/redis-py/issues/1022

**Comment by NoneGG** [comment]
@ycraaron 
Thank you for the detailed issue and pull request~

In this part, on encountering these two kinds of errors(`ConnectionError` & `TimeoutError`), only `TimeoutError` with `retry_on_timeout` set to False will not be retried, and it should be retried in other conditions.

So i think retry mechanism works as expected

**Comment by ycraaron** [comment]
I see, seems that the expected behavior is to retry for every connection error, but for timeout error, only retry when the user wants to. Then the logic is good.
Currently, we are using our own retry logic since we want to retry more than 1 time, it would be nice if the connection also allows setting a maximum retry count.

**Comment by NoneGG** [comment]
@ycraaron 
Actually `ConnectionError` or `TimeoutError` is not caught in retry part of the try-catch sentence. It will be raised if there is a network problem and commands are failed to send again. You can catch it in outer layer and make your retry.

**Comment by ycraaron** [comment]
@NoneGG Yes, exactly. Thanks a lot!
