### ISSUE TITLE
Exception when scan_iter() with StrictRedisCluster

### ISSUE THREAD

**Issue by khangnguyen** [NoneGG/aredis#92]
## Checklist

- Python version 
3.6
- Using hiredis or just Python parser
Python parser
- Using uvloop or just asyncio event loop
Asyncio
- Does issue exists against the `master` branch of aredis?
Yes

## Steps to reproduce
In this sample, scan_iter with StrictRedisCluster would raise exception
```python
import asyncio
from aredis import StrictRedisCluster

async def example():
    client = StrictRedisCluster(startup_nodes=settings.REDIS_CLUSTER, skip_full_coverage_check=True)
    keys = client.scan_iter()
    async for key in keys:
        print(key)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(example())
```

## Expected behavior
Redis keys are iterated and returned

## Actual behavior
```python
Traceback (most recent call last):
  File "sample.py", line 24, in <module>
    loop.run_until_complete(example())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "sample.py", line 16, in example
    async for key in keys:
  File "/usr/local/lib/python3.6/site-packages/aredis/commands/iter.py", line 23, in scan_iter
    cursor, data = await self.scan(cursor=cursor, match=match, count=count)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by NoneGG** [comment]
@khangnguyen Thank you for your bug report, it actually runs wrongly in cluster mode, will be fix soon

**Comment by NoneGG** [comment]
@khangnguyen fixed~ You can fetch code from master branch and test with your code

**Comment by NoneGG** [comment]
@khangnguyen 
This issue is closed now, feel free to open it again if there are related problems~ 
Thank you for your bug report again~
