### ISSUE TITLE
[Feature Request] Support socket keepalive options

### ISSUE THREAD

**Issue by stj** [NoneGG/aredis#99]
5 years ago redis-py added support for keepalive options on the socket connection to redis [1].
I like to use those in aredis as well. If an interest exist to add those to aredis I am willing to write a PR for it.

[1] https://github.com/andymccurdy/redis-py/commit/465e74dce8c30263f48f522a1def89e0a4b20d00

**Comment by NoneGG** [comment]
@stj Thanks, this feature request seems to be reasonable, it will be appreciate if you can write a pr for it~
